In [2]:
# !pip install pymupdf

import os
import numpy as np
import pandas as pd

In [3]:
BASE_URI_DE = r"Docsumo - IT MEET-20231205T023449Z-001\Docsumo - IT MEET\Data Extraction"
BASE_URI_TRAIN = os.path.join(BASE_URI_DE, "Train Files/")
BASE_URI_TEST = os.path.join(BASE_URI_DE, "Test Files/")

In [4]:
df = pd.read_csv(r"Docsumo - IT MEET-20231205T023449Z-001\Docsumo - IT MEET\Data Extraction\DE-TRAIN.csv")
df

,file_name,label,value,x0,y0,x2,y2
0,1040_file_1.pdf,Basic Information___First Name,Maureen,111.9,329.1,639.7,361.1
1,1040_file_1.pdf,Basic Information___Last Name,Hoffman,673.3,325.9,1258.6,359.5
2,1040_file_1.pdf,Income___One_F,23287.39,1405.7,1183.9,1594.4,1211.0
3,1040_file_1.pdf,Income___Three_B,8,1404.1,1386.8,1596.0,1412.3
4,1040_file_1.pdf,Income___Four_B,6,1404.1,1420.3,1599.2,1445.9
...,...,...,...,...,...,...,...
2182,1040_file_200.pdf,Income___Six_B,81325.78,1402.5,1487.4,1596.0,1511.4
2183,1040_file_200.pdf,Income___Nine,73661.413,1404.1,1618.4,1592.9,1644.0
2184,1040_file_200.pdf,Income___Ten,41023.34,1402.5,1652.0,1600.8,1679.2
2185,1040_file_200.pdf,Income___Eleven,75223.22,1402.5,1684.0,1599.2,1709.5
2186,1040_file_200.pdf,Income___Thirteen,88150.593,1400.9,1751.1,1597.6,1776.6

In [5]:
df['combined'] = df['label'].astype(str) + "," + df['x0'].astype(str) + "," + df['y0'].astype(str) + ',' + df['x2'].astype(str) + "," + df['y2'].astype(str)

In [6]:
df

,file_name,label,value,x0,y0,x2,y2,combined
0,1040_file_1.pdf,Basic Information___First Name,Maureen,111.9,329.1,639.7,361.1,"Basic Information___First Name,111.9,329.1,639..."
1,1040_file_1.pdf,Basic Information___Last Name,Hoffman,673.3,325.9,1258.6,359.5,"Basic Information___Last Name,673.3,325.9,1258..."
2,1040_file_1.pdf,Income___One_F,23287.39,1405.7,1183.9,1594.4,1211.0,"Income___One_F,1405.7,1183.9,1594.4,1211.0"
3,1040_file_1.pdf,Income___Three_B,8,1404.1,1386.8,1596.0,1412.3,"Income___Three_B,1404.1,1386.8,1596.0,1412.3"
4,1040_file_1.pdf,Income___Four_B,6,1404.1,1420.3,1599.2,1445.9,"Income___Four_B,1404.1,1420.3,1599.2,1445.9"
...,...,...,...,...,...,...,...,...
2182,1040_file_200.pdf,Income___Six_B,81325.78,1402.5,1487.4,1596.0,1511.4,"Income___Six_B,1402.5,1487.4,1596.0,1511.4"
2183,1040_file_200.pdf,Income___Nine,73661.413,1404.1,1618.4,1592.9,1644.0,"Income___Nine,1404.1,1618.4,1592.9,1644.0"
2184,1040_file_200.pdf,Income___Ten,41023.34,1402.5,1652.0,1600.8,1679.2,"Income___Ten,1402.5,1652.0,1600.8,1679.2"
2185,1040_file_200.pdf,Income___Eleven,75223.22,1402.5,1684.0,1599.2,1709.5,"Income___Eleven,1402.5,1684.0,1599.2,1709.5"
2186,1040_file_200.pdf,Income___Thirteen,88150.593,1400.9,1751.1,1597.6,1776.6,"Income___Thirteen,1400.9,1751.1,1597.6,1776.6"

In [7]:
unique_values = df['combined'].unique()
print(unique_values)

['Basic Information___First Name,111.9,329.1,639.7,361.1'
 'Basic Information___Last Name,673.3,325.9,1258.6,359.5'
 'Income___One_F,1405.7,1183.9,1594.4,1211.0'
 'Income___Three_B,1404.1,1386.8,1596.0,1412.3'
 'Income___Four_B,1404.1,1420.3,1599.2,1445.9'
 'Income___Five_B,1402.5,1450.7,1600.8,1479.4'
 'Income___Six_B,1402.5,1487.4,1596.0,1511.4'
 'Income___Eight,1404.1,1586.5,1596.0,1610.5'
 'Income___Nine,1404.1,1618.4,1592.9,1644.0'
 'Income___Eleven,1402.5,1684.0,1599.2,1709.5'
 'Income___Twelve,1404.1,1717.5,1597.6,1744.7'
 'Income___Fifteen,1404.1,1819.8,1596.0,1848.5'
 'Income___One_A,1405.7,1017.7,1591.3,1046.5'
 'Income___One_C,1405.7,1086.4,1591.3,1112.0'
 'Income___One_E,1404.1,1151.9,1594.4,1179.1'
 'Income___One_G,1404.1,1219.0,1596.0,1246.2'
 'Income___Seven,1404.1,1548.1,1597.6,1576.9'
 'Income___One_H,1404.1,1252.6,1596.0,1278.1'
 'Income___Ten,1402.5,1652.0,1600.8,1679.2'
 'Income___Thirteen,1400.9,1751.1,1597.6,1776.6'
 'Income___Two_B,1402.5,1353.2,1596.0,1377.2'
 'Income___Fourteen,1404.1,1784.6,1597.6,1811.8'
 'Income___One_D,1405.7,1116.8,1591.3,1147.1'
 'Income___One_Z,1404.1,1310.1,1596.0,1342.0'
 'Income___One_B,1404.1,1052.9,1597.6,1075.2']

In [8]:
labels_in_order = ["Basic Information___First Name", "Basic Information___Last Name",
                  "Income___One_A", "Income___One_B", "Income___One_C", "Income___One_D",
                  "Income___One_E", "Income___One_F", "Income___One_G", "Income___One_H", "Income___One_Z",
                  "Income___Two_B", "Income___Three_B", "Income___Four_B", "Income___Five_B",
                  "Income___Six_B", "Income___Seven", "Income___Eight", "Income___Nine",
                  "Income___Ten", "Income___Eleven", "Income___Twelve", "Income___Thirteen",
                  "Income___Fourteen", "Income___Fifteen"]

In [9]:
label_bbox = {}

for value in unique_values:
    contents = value.split(",")
    
    # remove zero after decimal and only keep integer
    for i in range(1, len(contents)):
        if int(float(contents[i])) - float(contents[i]) == 0.0:
            contents[i] = str(int(float(contents[i])))
    
    label_bbox[contents[0]] = contents[1:]
    
    
label_bbox
print(type(label_bbox["Basic Information___First Name"][0]))

<class 'str'>

In [10]:
if sorted(label_bbox.keys()) == sorted(labels_in_order):
    print("Arrays have the same elements.")
else:
    print("Arrays are different.")

Arrays have the same elements.

In [11]:
import fitz  # PyMuPDF

def extract_text_from_bbox(pdf_path, page_number, bbox):
    pdf_document = fitz.open(pdf_path)
    page = pdf_document[page_number]
    
    # the given bbox are highly scaled
    # PyMuPDF displays page size as Rect(0.0, 0.0, 612.0, 792.0)
    # but bbox in train dataset is maximum of 1600.8 wide
    # so scaling_factor used to sacle the bbox appropriately for PyMuPDF
    rect = page.rect
    # rect[2] is maximum width of opened page
    scaling_factor = rect[2] / 1700.0

    left, top, right, bottom = [x * scaling_factor for x in bbox]

    # Create a rectangle from the bbox
    rect = fitz.Rect(left, top, right, bottom)

    # Get the text in the specified bbox
    text = page.get_text("text", clip=rect)
    pdf_document.close()

    return text

In [12]:
def extract_label_value(pdf_path, label):
    page_number = 0
    bbox_coordinates = [float(x) for x in label_bbox[label]]
    
    extracted_text = extract_text_from_bbox(pdf_path, page_number, bbox_coordinates)
    return extracted_text.strip()

In [13]:
pdf_path = os.path.join(BASE_URI_TRAIN, "1040_file_100.pdf")
extract_label_value(pdf_path, "Income___Eleven")

'718.0'

In [14]:
def safe_float_conversion(value):
    try:
        result = float(value)
        return result
    except ValueError:
        return None

In [15]:
# json_list_train = []
# for filename in os.listdir(BASE_URI_TRAIN):
#     if filename.endswith(".pdf"):
#         for label in labels_in_order:
#             value = extract_label_value(os.path.join(BASE_URI_TRAIN, filename), label)
            
#             if value:
#                 if safe_float_conversion(value) != None:
#                     # if there is zero after decimal then only keep integer in value
#                     if int(float(value)) - float(value) == 0.0:
#                         value = str(int(float(value)))

#                 json_list_train.append({
#                     "file_name": str(filename),
#                     "label": label,
#                     "value": value,
#                     "x0": label_bbox[label][0],
#                     "y0": label_bbox[label][1],
#                     "x2": label_bbox[label][2],
#                     "y2": label_bbox[label][3],
#                 })

In [16]:
# len(json_list_train)

In [17]:
# print(json_list_train[:10])

In [18]:
# generated_train_df = pd.DataFrame(json_list_train)
# generated_train_df

In [19]:
# generated_train_df.to_csv('DE-TRAIN-Inferred.csv', index=False)

In [20]:
df_train_inferred = pd.read_csv("DE-TRAIN-Inferred.csv")
df_train_inferred

,file_name,label,value,x0,y0,x2,y2
0,1040_file_1.pdf,Basic Information___First Name,Maureen,111.9,329.1,639.7,361.1
1,1040_file_1.pdf,Basic Information___Last Name,Hoffman,673.3,325.9,1258.6,359.5
2,1040_file_1.pdf,Income___One_F,23287.39,1405.7,1183.9,1594.4,1211.0
3,1040_file_1.pdf,Income___Three_B,8,1404.1,1386.8,1596.0,1412.3
4,1040_file_1.pdf,Income___Four_B,6,1404.1,1420.3,1599.2,1445.9
...,...,...,...,...,...,...,...
2182,1040_file_99.pdf,Income___One_Z,8879,1404.1,1310.1,1596.0,1342.0
2183,1040_file_99.pdf,Income___Two_B,56280,1402.5,1353.2,1596.0,1377.2
2184,1040_file_99.pdf,Income___Seven,98548,1404.1,1548.1,1597.6,1576.9
2185,1040_file_99.pdf,Income___Eleven,90523.168,1402.5,1684.0,1599.2,1709.5
2186,1040_file_99.pdf,Income___Thirteen,37298.86,1400.9,1751.1,1597.6,1776.6

In [21]:
"""Checking if df_train_inferred and df are same to check 100% accuracy"""
#Dropping combined column of df
df = df.drop('combined', axis=1)

# Sort the DataFrames by rows to ensure the order doesn't matter
df_sorted = df.sort_values(by=list(df.columns)).reset_index(drop=True)
df_train_inferred_sorted = df_train_inferred.sort_values(by=list(df_train_inferred.columns)).reset_index(drop=True)

# Check if the sorted DataFrames are exactly equal
are_equal = df_sorted.equals(df_train_inferred_sorted)

if are_equal:
    print("DataFrames have the same contents (ignoring order).")
else:
    print("DataFrames do not have the same contents (ignoring order).")

DataFrames have the same contents (ignoring order).

---
## TEST
---

In [22]:
test_df = pd.read_csv(r"Docsumo - IT MEET-20231205T023449Z-001\Docsumo - IT MEET\Data Extraction\DE-TEST.csv")
test_df

            file_name  label  value  x0  y0  x2  y2
0    1040_file_10.pdf    NaN    NaN NaN NaN NaN NaN
1    1040_file_16.pdf    NaN    NaN NaN NaN NaN NaN
2    1040_file_17.pdf    NaN    NaN NaN NaN NaN NaN
3    1040_file_19.pdf    NaN    NaN NaN NaN NaN NaN
4    1040_file_31.pdf    NaN    NaN NaN NaN NaN NaN
5    1040_file_46.pdf    NaN    NaN NaN NaN NaN NaN
6    1040_file_56.pdf    NaN    NaN NaN NaN NaN NaN
7    1040_file_57.pdf    NaN    NaN NaN NaN NaN NaN
8    1040_file_61.pdf    NaN    NaN NaN NaN NaN NaN
9    1040_file_66.pdf    NaN    NaN NaN NaN NaN NaN
10   1040_file_67.pdf    NaN    NaN NaN NaN NaN NaN
11   1040_file_68.pdf    NaN    NaN NaN NaN NaN NaN
12   1040_file_69.pdf    NaN    NaN NaN NaN NaN NaN
13   1040_file_70.pdf    NaN    NaN NaN NaN NaN NaN
14   1040_file_76.pdf    NaN    NaN NaN NaN NaN NaN
15   1040_file_77.pdf    NaN    NaN NaN NaN NaN NaN
16   1040_file_79.pdf    NaN    NaN NaN NaN NaN NaN
17   1040_file_83.pdf    NaN    NaN NaN NaN NaN NaN
18   1040_file_85.pdf    NaN    NaN NaN NaN NaN NaN
19   1040_file_94.pdf    NaN    NaN NaN NaN NaN NaN
20   1040_file_96.pdf    NaN    NaN NaN NaN NaN NaN
21  1040_file_105.pdf    NaN    NaN NaN NaN NaN NaN
22  1040_file_116.pdf    NaN    NaN NaN NaN NaN NaN
23  1040_file_125.pdf    NaN    NaN NaN NaN NaN NaN
24  1040_file_126.pdf    NaN    NaN NaN NaN NaN NaN
25  1040_file_129.pdf    NaN    NaN NaN NaN NaN NaN
26  1040_file_133.pdf    NaN    NaN NaN NaN NaN NaN
27  1040_file_136.pdf    NaN    NaN NaN NaN NaN NaN
28  1040_file_138.pdf    NaN    NaN NaN NaN NaN NaN
29  1040_file_149.pdf    NaN    NaN NaN NaN NaN NaN
30  1040_file_151.pdf    NaN    NaN NaN NaN NaN NaN
31  1040_file_153.pdf    NaN    NaN NaN NaN NaN NaN
32  1040_file_159.pdf    NaN    NaN NaN NaN NaN NaN
33  1040_file_165.pdf    NaN    NaN NaN NaN NaN NaN
34  1040_file_166.pdf    NaN    NaN NaN NaN NaN NaN
35  1040_file_171.pdf    NaN    NaN NaN NaN NaN NaN
36  1040_file_175.pdf    NaN    NaN NaN NaN NaN NaN
37  1040_file_178.pdf    NaN    NaN NaN NaN NaN NaN
38  1040_file_183.pdf    NaN    NaN NaN NaN NaN NaN
39  1040_file_187.pdf    NaN    NaN NaN NaN NaN NaN

In [23]:
test_file_list = list(test_df["file_name"].values)
test_file_list[:5]

['1040_file_10.pdf',
 '1040_file_16.pdf',
 '1040_file_17.pdf',
 '1040_file_19.pdf',
 '1040_file_31.pdf']

In [24]:
# json_list_test = []

# for filename in test_file_list:
#     if filename.endswith(".pdf"):
#         for label in labels_in_order:
#             value = extract_label_value(os.path.join(r"C:\Users\Acer\codes\ai_competition_it_meet\Docsumo - IT MEET-20231205T023449Z-001\Docsumo - IT MEET\Data Extraction\Test Files", filename), label)
            
#             if value:
#                 if safe_float_conversion(value) != None:
#                     # if there is zero after decimal then only keep integer in value
#                     if int(float(value)) - float(value) == 0.0:
#                         value = str(int(float(value)))

#                 json_list_test.append({
#                     "file_name": str(filename),
#                     "label": label,
#                     "value": value,
#                     "x0": label_bbox[label][0],
#                     "y0": label_bbox[label][1],
#                     "x2": label_bbox[label][2],
#                     "y2": label_bbox[label][3],
#                 })

In [25]:
# print(json_list_test[:10])

In [26]:
# len(json_list_test)

In [27]:
# generated_test_df = pd.DataFrame(json_list_test)
# generated_test_df

In [28]:
# generated_test_df.to_csv('DE-TEST-Inferred.csv', index=False)

In [29]:
df_test_inferred = pd.read_csv("DE-TEST-Inferred.csv")

---
## Evaluation
---

In [30]:
df_merged_train = pd.merge(df, df_train_inferred, on=['file_name', 'label'])
df_merged_train

,file_name,label,value_x,x0_x,y0_x,x2_x,y2_x,value_y,x0_y,y0_y,x2_y,y2_y
0,1040_file_1.pdf,Basic Information___First Name,Maureen,111.9,329.1,639.7,361.1,Maureen,111.9,329.1,639.7,361.1
1,1040_file_1.pdf,Basic Information___Last Name,Hoffman,673.3,325.9,1258.6,359.5,Hoffman,673.3,325.9,1258.6,359.5
2,1040_file_1.pdf,Income___One_F,23287.39,1405.7,1183.9,1594.4,1211.0,23287.39,1405.7,1183.9,1594.4,1211.0
3,1040_file_1.pdf,Income___Three_B,8,1404.1,1386.8,1596.0,1412.3,8,1404.1,1386.8,1596.0,1412.3
4,1040_file_1.pdf,Income___Four_B,6,1404.1,1420.3,1599.2,1445.9,6,1404.1,1420.3,1599.2,1445.9
...,...,...,...,...,...,...,...,...,...,...,...,...
2182,1040_file_200.pdf,Income___Six_B,81325.78,1402.5,1487.4,1596.0,1511.4,81325.78,1402.5,1487.4,1596.0,1511.4
2183,1040_file_200.pdf,Income___Nine,73661.413,1404.1,1618.4,1592.9,1644.0,73661.413,1404.1,1618.4,1592.9,1644.0
2184,1040_file_200.pdf,Income___Ten,41023.34,1402.5,1652.0,1600.8,1679.2,41023.34,1402.5,1652.0,1600.8,1679.2
2185,1040_file_200.pdf,Income___Eleven,75223.22,1402.5,1684.0,1599.2,1709.5,75223.22,1402.5,1684.0,1599.2,1709.5
2186,1040_file_200.pdf,Income___Thirteen,88150.593,1400.9,1751.1,1597.6,1776.6,88150.593,1400.9,1751.1,1597.6,1776.6

In [54]:
print(df_merged_train["label"].unique())

['Basic Information___First Name' 'Basic Information___Last Name'
 'Income___One_F' 'Income___Three_B' 'Income___Four_B' 'Income___Five_B'
 'Income___Six_B' 'Income___Eight' 'Income___Nine' 'Income___Eleven'
 'Income___Twelve' 'Income___Fifteen' 'Income___One_A' 'Income___One_C'
 'Income___One_E' 'Income___One_G' 'Income___Seven' 'Income___One_H'
 'Income___Ten' 'Income___Thirteen' 'Income___Two_B' 'Income___Fourteen'
 'Income___One_D' 'Income___One_Z' 'Income___One_B']

In [71]:
from sklearn.metrics import mean_squared_error, r2_score

df_merged_train_filtered = df_merged_train[(df_merged_train['label'] != 'Basic Information___First Name') & (df_merged_train['label'] != 'Basic Information___Last Name')]
train_mse = mean_squared_error(df_merged_train_filtered["value_x"], df_merged_train_filtered["value_y"])
train_r2 = r2_score(df_merged_train_filtered["value_x"], df_merged_train_filtered["value_y"])
print(train_mse, train_r2)

0.0 1.0